# Generated by Django 2.2.6 on 2020-01-02 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('senha', models.IntegerField(verbose_name='senha')),
                ('confirmarSenha', models.IntegerField(verbose_name='confirmarSenha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('seconds', models.IntegerField()),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('senha', models.IntegerField(verbose_name='senha')),
                ('confirmarSenha', models.IntegerField(verbose_name='confirmarSenha')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resposta', models.IntegerField(choices=[('0', 'Muito-Raramente'), ('1', 'As-Vezes'), ('2', 'Frequentemente'), ('3', 'Sempre')], verbose_name='resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Testes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(choices=[('1', 'Estados-do-Ego'), ('2', 'Personalidade')], verbose_name='nome')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testes', to='app.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='titulo')),
                ('descricao', models.TextField(max_length=130, verbose_name='descrica')),
                ('data_expiracao', models.DateField(verbose_name='data')),
                ('prioridade', models.CharField(choices=[('A', 'ALTA'), ('N', 'NORMAL'), ('B', 'BAIXA')], max_length=1, verbose_name='prioridade')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Ego'), ('2', 'Personalidade')], max_length=1, verbose_name='tipo')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionario', to='app.Aluno')),
                ('respostas', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(verbose_name='nome')),
                ('professor', models.ManyToManyField(to='app.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='ComplementoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complementoUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
