# Generated by Django 2.2.6 on 2020-01-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tecnico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tecnico',
            new_name='Alunos',
        ),
    ]
