# Generated by Django 2.2.6 on 2020-01-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200103_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alunos',
        ),
    ]
