# Generated by Django 2.2.6 on 2020-01-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='pergunta',
        ),
    ]
