# Generated by Django 2.2.6 on 2020-01-16 21:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.FloatField()),
                ('status', models.CharField(choices=[('P', 'pedido realizado'), ('F', 'fazendo'), ('E', 'saiu para entrega')], max_length=1)),
                ('observacoes', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
    ]
